### ISSUE TITLE
Access to your repository

### ISSUE THREAD

**Issue by SirPando** [rbakosBTU/WebDoc-WiSE21#1]
Hello Rene and Jessica,

can you pls add [me](https://github.com/SirPando) and mr [Bui](https://github.com/BMD91) to your repository? We are your Clients.
Thanks in advance,

Andreas Eberle

**Comment by rbakosBTU** [comment]
Hello @SirPando,

I just sent you both an invite to the repository. If you have any further questions, feel free to contact us.
