### ISSUE TITLE
gh-pages setting

### ISSUE THREAD

**Issue by SirPando** [rbakosBTU/WebDoc-WiSE21#3]
@rbakosBTU Can you pls change the settings for gh-pages so it works from branch develop/docs pls? To do so, you need to go to ``Settings``, here on github, then on the left side you will find ``Pages`` and there pls change the ``Source branch`` from ``main`` to ``develop`` and also from ``/(root)`` to ``/docs``. Then press ``Save``. Pls confirm when done, thanks.

**Comment by rbakosBTU** [comment]
@SirPando Done! Please confirm if it worked for you.

**Comment by SirPando** [comment]
working fine, thx 👍
